### ISSUE TITLE
Cached response did not work with custom URLSessionDelegate

### ISSUE THREAD

**Issue by wpcfan** [RxSwiftCommunity/RxHttpClient#43]
I created the following custom delegate

```
class SelfSignedSSLSessionDelegate: NSURLSessionDataEventsObserver {
    
    func urlSession(_ session: URLSession, didReceive challenge: URLAuthenticationChallenge, completionHandler: @escaping (URLSession.AuthChallengeDisposition, URLCredential?) -> Void) {
        if(challenge.protectionSpace.authenticationMethod == NSURLAuthenticationMethodServerTrust) {
            if(challenge.protectionSpace.host == "xxx.xx.com") {
                let credential = URLCredential(trust: challenge.protectionSpace.serverTrust!)
                completionHandler(.useCredential, credential)
            } else {
                completionHandler(.cancelAuthenticationChallenge, nil)
            }
        } else {
            completionHandler(.performDefaultHandling, nil)
        }
    }
}
```

and created the following client

```
let plugins: [RequestPluginType] = [] //[NetworkActivityIndicatorPlugin()]
        let delegate = SelfSignedSSLSessionDelegate()
        let cacheDirectory = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first!.appendingPathComponent("Cache")
        try! FileManager.default.createDirectory(atPath: cacheDirectory.path, withIntermediateDirectories: true, attributes: nil)
        // instance of UrlRequestFileSystemCacheProvider that will store cached data in specified directory
        let urlCacheProvider = UrlRequestFileSystemCacheProvider(cacheDirectory: cacheDirectory)
        return HttpClient(
            sessionConfiguration: .default,
            urlRequestCacheProvider: urlCacheProvider,
//            requestPlugin: CompositeRequestPlugin(plugins: plugins),
            sessionDelegate: delegate)
```

After request issued, I checked the Cache folder, there is nothing in the folder

[UPDATED]

After some debugging, I found out the library only caches the GET requests, of course it is correct when properly using REST API. But in the real world, there are some services using POST to get data, I know this is bad, but we cannot change the third-party services. So is there anyway we can handle this, e.g. provide another param in requestData method to let developer decide if the request will be cached?

**Comment by reloni** [comment]
Hello @wpcfan you are correct, now library caches only get requests and I'm not sure about caching other types of requests. Actually we can do that, but it requires a little bit of rewriting:(

**Comment by wpcfan** [comment]
@reloni thanks for quick reply

Currently, all the cache logic located in HttpClientType+Extentions, so can we simply remove ` urlRequest.httpMethod == HttpMethod.get.rawValue` in the conditional clause? because requestCacheMode did give the enough information to determine if and how the request will/will not be cached?

```
func requestData(_ urlRequest: URLRequest, requestCacheMode: CacheMode = CacheMode())	-> Observable<Data> {
...
                    let cachedRequest: Observable<Data> = {
			if urlRequest.httpMethod == HttpMethod.get.rawValue,  requestCacheMode.returnCachedResponse, let url = urlRequest.url, let cached = urlRequestCacheProvider?.load(resourceUrl: url) {
				// return cached response
				return Observable.just(cached)
			}
			return Observable.empty()
		}()
...
                     case .success:
					guard let errorResponse = errorResponse else {
						let requestData = dataCacheProvider.getData()
						
						if urlRequest.httpMethod == HttpMethod.get.rawValue, requestCacheMode.cacheResponse, let url = urlRequest.url  {
							// sache response
							self?.urlRequestCacheProvider?.save(resourceUrl: url, data: requestData)
						}
						
						// if we don't have errorResponse, request completed successfuly and we simply return data
						return Observable.just(requestData)
					}
					
					return Observable.error(HttpClientError.invalidResponse(response: errorResponse, data: dataCacheProvider.getData()))
....
}
```

**Comment by reloni** [comment]
I'm now sure about this change. For example caching DELETE requests makes no sense, and cached response for POST or PUT request also may be counterintuitive. But I saw WEB api with POST requests acting like GET, so in some cases it may be useful. So maybe it would be ok to add additional customization parameter and allow caller to choose what he or she want to cache.

**Comment by reloni** [comment]
Hellow @wpcfan 
I implemented this customization in [custom-caching](https://github.com/RxSwiftCommunity/RxHttpClient/tree/custom-caching) branch. Please check it out and if it's ok I will merge it into master.
Required methods should be specified in CacheMode instance:
`CacheMode(cacheResponse: true, returnCachedResponse: true, invokeRequest: true, cacheHttpMethods: [.get, .post, .put])`

**Comment by wpcfan** [comment]
It just works! thanks for the great work!
